# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Plugins
plugins: [jekyll-paginate]

# Setup
title:            'STAT 215A'
tagline:          ''
description:      '[Fall 2021] <br /> Bin Yu <br />'
url:              "https://yu-group.github.io/stat-215a-fall-2020/"
baseurl:          "/stat-215a-fall-2021"

author:
  name:           'Bin Yu, James Duncan'
  url:            "https://yu-group.github.io/stat-215a-fall-2021/"

paginate:         5

repository: Yu-Group/stat-215a-fall-2021

gems: ["jekyll-github-metadata"]
